name: SuperShop
version: 1.0.0 BETA
author: SFCTeam
description: People has been dreaming for ages, now its a reality!
main: SFC\SuperShop\Main
api: [2.0.0, 2.1.0]
commands: "/enchanter" 
  shop:
   usage: "/enchanter"
